#!/bin/bash
#
# This script launches a Docker container for development.

set -euo pipefail

ROOT=$(realpath "$(dirname "$0")/..")

IMAGE_NAME=ruby:3

VOLUMNE_HOME=highcarb-slides-home

# Create a volume for the $HOME in the container, and change its owner to the
# user running this script.
prepare_volume() {
  if [ -z "$(docker volume inspect -f OK $VOLUMNE_HOME 2> /dev/null)" ]
  then
    (
      OWNER="$(id -u):$(id -g)"

      set -x

      docker volume create $VOLUMNE_HOME

      docker run --rm         \
        -v $VOLUMNE_HOME:/vol \
        $IMAGE_NAME           \
        sh -c "chown '$OWNER' /vol"
    )
  fi
}

prepare_volume

if [ -t 0 ] && [ -t 1 ]
then
  io_args=(--tty --interactive)
else
  io_args=()
fi

CONTAINER_NAME="$(basename "$ROOT")-$$"
USERID=$(id -u)

set -x
docker run                           \
  --rm                               \
  "${io_args[@]}"                    \
  --name "$CONTAINER_NAME"           \
  --user "$USERID"                   \
  --volume "$VOLUMNE_HOME:/home/app" \
  --volume "$ROOT:/source"           \
  --env HOME=/home/app               \
  --env GEM_HOME=/home/app/gems      \
  --workdir /source                  \
  --entrypoint /bin/bash             \
  $IMAGE_NAME                        \
  "$@"
